"""Tests for CLI helper functions."""

from __future__ import annotations

from pathlib import Path

import pytest

from alpha_gen.cli.helpers import format_markdown, save_markdown_report


class TestFormatMarkdown:
    """Tests for format_markdown function."""

    def test_basic_formatting(self) -> None:
        """Test basic markdown formatting."""
        result = format_markdown(
            title="Test Report",
            content="This is test content.",
        )

        assert "# Test Report" in result
        assert "## Analysis" in result
        assert "This is test content." in result
        assert "*Generated by Alpha Gen" in result

    def test_with_metadata(self) -> None:
        """Test markdown formatting with metadata."""
        result = format_markdown(
            title="Test Report",
            content="Content",
            metadata={"ticker": "AAPL", "duration_ms": "1234"},
        )

        assert "## Metadata" in result
        assert "**ticker:** AAPL" in result
        assert "**duration_ms:** 1234" in result

    def test_with_losers_data(self) -> None:
        """Test markdown formatting with losers data."""
        losers = [
            {
                "ticker": "AAPL",
                "name": "Apple Inc.",
                "price": "$150.00",
                "change": "-5.2%",
                "volume": "1M",
            },
            {
                "ticker": "MSFT",
                "name": "Microsoft Corporation",
                "price": "$300.00",
                "change": "-3.1%",
                "volume": "2M",
            },
        ]

        result = format_markdown(
            title="Opportunities",
            content="Analysis content",
            losers_data=losers,
        )

        assert "## Top Losers Analyzed" in result
        assert "| Ticker | Name | Price | Change | Volume |" in result
        assert "| AAPL |" in result
        assert "| MSFT |" in result


class TestSaveMarkdownReport:
    """Tests for save_markdown_report function."""

    def test_save_report(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        """Test saving markdown report to file."""
        # Mock the config to use tmp_path
        from alpha_gen.core.config.settings import AppConfig, OutputConfig

        test_config = AppConfig(output=OutputConfig(output_dir=tmp_path))

        def mock_get_config() -> AppConfig:
            return test_config

        monkeypatch.setattr("alpha_gen.cli.helpers.get_config", mock_get_config)

        # Save a report
        filepath = save_markdown_report(
            title="Test Report",
            content="Test content",
            metadata={"ticker": "AAPL"},
            filename_prefix="test",
        )

        # Verify file was created
        assert filepath.exists()
        assert filepath.parent == tmp_path
        assert filepath.name.startswith("test_")
        assert filepath.suffix == ".md"

        # Verify content
        content = filepath.read_text(encoding="utf-8")
        assert "# Test Report" in content
        assert "Test content" in content
        assert "**ticker:** AAPL" in content

    def test_filename_format(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Test that filename includes timestamp."""
        from alpha_gen.core.config.settings import AppConfig, OutputConfig

        test_config = AppConfig(output=OutputConfig(output_dir=tmp_path))

        def mock_get_config() -> AppConfig:
            return test_config

        monkeypatch.setattr("alpha_gen.cli.helpers.get_config", mock_get_config)

        filepath = save_markdown_report(
            title="Report",
            content="Content",
            filename_prefix="research_AAPL",
        )

        # Filename should be: research_AAPL_YYYYMMDD_HHMMSS.md
        assert filepath.name.startswith("research_AAPL_")
        assert filepath.suffix == ".md"
        # Check timestamp format (8 digits for date + underscore + 6 digits for time)
        parts = filepath.stem.split("_")
        assert len(parts) >= 3
        assert len(parts[-2]) == 8  # YYYYMMDD
        assert len(parts[-1]) == 6  # HHMMSS
