"""Helper functions for CLI output formatting."""

from __future__ import annotations

from typing import Any

from rich import print as rprint
from rich.panel import Panel
from rich.table import Table


def format_markdown(
    title: str,
    content: str,
    metadata: dict[str, Any] | None = None,
    losers_data: list[dict[str, Any]] | None = None,
) -> str:
    """Format output as markdown.

    Args:
        title: Report title
        content: Main content
        metadata: Optional metadata dictionary
        losers_data: Optional list of losers for opportunities command

    Returns:
        Markdown formatted string
    """
    lines: list[str] = []

    # Title
    lines.append(f"# {title}")
    lines.append("")

    # Metadata section
    if metadata:
        lines.append("## Metadata")
        lines.append("")
        for key, value in metadata.items():
            if value is not None:
                lines.append(f"- **{key}:** {value}")
        lines.append("")

    # Losers table (for opportunities command)
    if losers_data:
        lines.append("## Top Losers Analyzed")
        lines.append("")
        lines.append("| Ticker | Name | Price | Change | Volume |")
        lines.append("|--------|------|-------|--------|--------|")
        for loser in losers_data[:10]:
            lines.append(
                f"| {loser.get('ticker', 'N/A')} | "
                f"{loser.get('name', 'N/A')[:30]} | "
                f"{loser.get('price', 'N/A')} | "
                f"{loser.get('change', 'N/A')} | "
                f"{loser.get('volume', 'N/A')} |"
            )
        lines.append("")

    # Main content
    lines.append("## Analysis")
    lines.append("")
    lines.append(content)
    lines.append("")

    # Footer
    lines.append("---")
    lines.append("*Generated by Alpha Gen - AI Investment Research Assistant*")

    return "\n".join(lines)


def output_result(
    output_format: str,
    title: str,
    content: str,
    metadata: dict[str, Any] | None = None,
    losers_data: list[dict[str, Any]] | None = None,
) -> None:
    """Output result in the specified format.

    Args:
        output_format: Output format (text, json, markdown)
        title: Report title
        content: Main content
        metadata: Optional metadata
        losers_data: Optional losers data
    """
    if output_format == "json":
        import json

        result: dict[str, Any] = {
            "title": title,
            "content": content,
            "metadata": metadata or {},
        }
        if losers_data:
            result["losers"] = losers_data
        rprint(json.dumps(result, indent=2, default=str))
    elif output_format == "markdown":
        markdown_content = format_markdown(
            title=title,
            content=content,
            metadata=metadata,
            losers_data=losers_data,
        )
        rprint(markdown_content)
    else:
        # Default to text/rich output
        if losers_data:
            table = Table(title="Top Losers Analyzed")
            table.add_column("Ticker")
            table.add_column("Name")
            table.add_column("Price")
            table.add_column("Change")
            table.add_column("Volume")

            for loser in losers_data[:10]:
                table.add_row(
                    loser.get("ticker", "N/A"),
                    loser.get("name", "N/A")[:30],
                    loser.get("price", "N/A"),
                    loser.get("change", "N/A"),
                    loser.get("volume", "N/A"),
                )

            rprint(table)
            rprint("")

        rprint(
            Panel(
                content,
                title=title,
                expand=False,
            )
        )
