"""Helper functions for CLI output formatting."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

from rich import print as rprint
from rich.panel import Panel
from rich.table import Table

from alpha_gen.core.config.settings import get_config


def format_markdown(
    title: str,
    content: str,
    metadata: dict[str, Any] | None = None,
    losers_data: list[dict[str, Any]] | None = None,
) -> str:
    """Format output as markdown.

    Args:
        title: Report title
        content: Main content
        metadata: Optional metadata dictionary
        losers_data: Optional list of losers for opportunities command

    Returns:
        Markdown formatted string
    """
    lines: list[str] = []

    # Title
    lines.append(f"# {title}")
    lines.append("")

    # Metadata section
    if metadata:
        lines.append("## Metadata")
        lines.append("")
        for key, value in metadata.items():
            if value is not None:
                lines.append(f"- **{key}:** {value}")
        lines.append("")

    # Losers table (for opportunities command)
    if losers_data:
        lines.append("## Top Losers Analyzed")
        lines.append("")
        lines.append("| Ticker | Name | Price | Change | Volume |")
        lines.append("|--------|------|-------|--------|--------|")
        for loser in losers_data[:10]:
            lines.append(
                f"| {loser.get('ticker', 'N/A')} | "
                f"{loser.get('name', 'N/A')[:30]} | "
                f"{loser.get('price', 'N/A')} | "
                f"{loser.get('change', 'N/A')} | "
                f"{loser.get('volume', 'N/A')} |"
            )
        lines.append("")

    # Main content
    lines.append("## Analysis")
    lines.append("")
    lines.append(content)
    lines.append("")

    # Footer
    lines.append("---")
    lines.append("*Generated by Alpha Gen - AI Investment Research Assistant*")

    return "\n".join(lines)


def save_markdown_report(
    title: str,
    content: str,
    metadata: dict[str, Any] | None = None,
    losers_data: list[dict[str, Any]] | None = None,
    filename_prefix: str = "report",
) -> Path:
    """Save markdown report to output directory.

    Args:
        title: Report title
        content: Main content
        metadata: Optional metadata
        losers_data: Optional losers data
        filename_prefix: Prefix for the filename (e.g., 'research', 'opportunities')

    Returns:
        Path to the saved file
    """
    config = get_config()
    config.output.ensure_output_dir()

    # Generate filename with timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{filename_prefix}_{timestamp}.md"
    filepath = config.output.output_dir / filename

    # Format as markdown
    markdown_content = format_markdown(
        title=title,
        content=content,
        metadata=metadata,
        losers_data=losers_data,
    )

    # Write to file
    filepath.write_text(markdown_content, encoding="utf-8")

    return filepath


def output_result(
    output_format: str,
    title: str,
    content: str,
    metadata: dict[str, Any] | None = None,
    losers_data: list[dict[str, Any]] | None = None,
    save: bool = False,
    filename_prefix: str = "report",
) -> None:
    """Output result in the specified format.

    Args:
        output_format: Output format (text, json, markdown)
        title: Report title
        content: Main content
        metadata: Optional metadata
        losers_data: Optional losers data
        save: Whether to save the report as a markdown file
        filename_prefix: Prefix for saved filename
    """
    if output_format == "json":
        import json

        result: dict[str, Any] = {
            "title": title,
            "content": content,
            "metadata": metadata or {},
        }
        if losers_data:
            result["losers"] = losers_data
        rprint(json.dumps(result, indent=2, default=str))
    elif output_format == "markdown":
        markdown_content = format_markdown(
            title=title,
            content=content,
            metadata=metadata,
            losers_data=losers_data,
        )
        rprint(markdown_content)
    else:
        # Default to text/rich output
        if losers_data:
            table = Table(title="Top Losers Analyzed")
            table.add_column("Ticker")
            table.add_column("Name")
            table.add_column("Price")
            table.add_column("Change")
            table.add_column("Volume")

            for loser in losers_data[:10]:
                table.add_row(
                    loser.get("ticker", "N/A"),
                    loser.get("name", "N/A")[:30],
                    loser.get("price", "N/A"),
                    loser.get("change", "N/A"),
                    loser.get("volume", "N/A"),
                )

            rprint(table)
            rprint("")

        rprint(
            Panel(
                content,
                title=title,
                expand=False,
            )
        )

    # Save to file if requested
    if save:
        saved_path = save_markdown_report(
            title=title,
            content=content,
            metadata=metadata,
            losers_data=losers_data,
            filename_prefix=filename_prefix,
        )
        rprint(f"\n[green]✓[/green] Report saved to: [cyan]{saved_path}[/cyan]")
